version: "3.9"

services:
  web:
    build:
      context: ./app
    env_file: .env.prod
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    networks:
      - prod_net
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
    - "5432:5432"
    env_file: .env.prod
    volumes:
      - prod_pgdata:/var/lib/postgresql/data
    networks:
      - prod_net

networks:
  prod_net:

volumes:
  prod_pgdata:
