version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - dev_network
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: mysql:8.0
    env_file:
      - .env
    networks:
      - dev_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  dev_network:


volumes:
  db_data:
